INSERT INTO USERS (USR_NAME, USR_ACTIVE, USR_CREATED)
VALUES ('John', True, '2007-12-03');
INSERT INTO USERS (USR_NAME, USR_ACTIVE, USR_CREATED)
VALUES ('Peter', True, '2007-12-04');
INSERT INTO USERS (USR_NAME, USR_ACTIVE, USR_CREATED)
VALUES ('Linda', True, '2007-12-05');

INSERT INTO COUNTRIES (CNT_CODE, CNT_TITLE, CNT_CREATED)
VALUES ('ISL', 'Israel', '2020-10-03');
INSERT INTO COUNTRIES (CNT_CODE, CNT_TITLE, CNT_CREATED)
VALUES ('ESP', 'Spain', '2020-10-05');
INSERT INTO COUNTRIES (CNT_CODE, CNT_TITLE, CNT_CREATED)
VALUES ('USA', 'United States of America', '2020-10-06');

INSERT INTO NUMBERS (CNT_ID, NUM_NUMBER, NUM_CREATED)
VALUES (1, '+234567', '2007-12-01');
INSERT INTO NUMBERS (CNT_ID, NUM_NUMBER, NUM_CREATED)
VALUES (2, '+453244', '2007-12-02');
INSERT INTO NUMBERS (CNT_ID, NUM_NUMBER, NUM_CREATED)
VALUES (3, '+908765', '2007-12-03');

INSERT INTO SEND_LOG (USR_ID, NUM_ID, LOG_MESSAGE, LOG_SUCCESS, LOG_CREATED)
VALUES (1, 1, 'Connection established', True, '2021-01-20');
INSERT INTO SEND_LOG (USR_ID, NUM_ID, LOG_MESSAGE, LOG_SUCCESS, LOG_CREATED)
VALUES (2, 2, 'Connection established', True, '2021-01-20');
INSERT INTO SEND_LOG (USR_ID, NUM_ID, LOG_MESSAGE, LOG_SUCCESS, LOG_CREATED)
VALUES (2, 2, 'Connection failed', False, '2021-01-21');
INSERT INTO SEND_LOG (USR_ID, NUM_ID, LOG_MESSAGE, LOG_SUCCESS, LOG_CREATED)
VALUES (3, 3, 'Connection failed', False, '2021-01-21');